"""user and message tables

Revision ID: 274784499962
Revises: 
Create Date: 2021-03-14 00:20:26.596944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '274784499962'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('slack_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('slack_id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('importance', sa.String(), nullable=True),
    sa.Column('user_uuid', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
